export type DashboardPanel = { title: string; metricIds: string[]; note?: string };

export const DASHBOARDS: DashboardPanel[] = [
  { title: "Eco Overview", metricIds: ["m_income", "e_income", "m_excess", "e_excess"] },
  { title: "Stall & Build Power", metricIds: ["metal_stall", "energy_stall", "build_power_util", "stall_sync"],
    note: "stall_sync: running corr of metal-stall vs energy-stall — near 1.0 means stalls are synchronized all-in investment dips (elite pattern); low means one-sided drift. Undefined (gap) until the first stall." },
  { title: "Allocation (eco vs army)", metricIds: ["alloc_eco", "alloc_bp", "alloc_army", "alloc_defense"],
    note: "Beta: role bucketing not yet validated against real captures." },
  { title: "Converter", metricIds: ["mm_use", "mm_capacity", "mm_use_rec", "mm_capacity_rec", "e_excess"],
    note: "mm_use/mm_capacity are native gadget params (absent in pre-addendum captures); the _rec variants are reconstructed from converter units' energyUse — uptime = use/capacity." },
  { title: "On-Base %", metricIds: ["obp", "converter_uptime"],
    note: "Beta: resource-fundamentals subset (no stall, no overflow). Com/factory idleness, spot claims, and intel freshness pending real data + map inputs." },
  { title: "OBP Breakdown", metricIds: ["obp", "obp_stall_m", "obp_stall_e", "obp_waste_m", "obp_waste_e", "obp_idle_bp", "obp_bp_capacity"],
    note: "OBP v3: alive-gated (dead frames excluded) with six components (incl. idle-BP and BP-capacity vs the guide ratio: max(40×m_income, 2×(e_income − converter draw))) — the leak curves are cumulative violation fractions (best viewed one player at a time)." },
  { title: "Build Power", metricIds: ["bp_available", "bp_used", "bp_used_eco", "bp_used_bp", "bp_used_army", "bp_used_defense"],
    note: "Available vs applied BP (same unit, one scale; used-series smoothed over 5s). The role suboptions split applied BP by what it was building — toggle via the Variables strip. Repairs/assist after completion not counted. build_power_util is the normalized (0-1) version." },
  { title: "Guide Ratio", metricIds: ["ratio_balance", "ratio_share_bp", "ratio_share_m", "ratio_share_e"],
    note: "Closeness to the 200 BP : 5 m/s : 100 e/s guide ratio, scale-free. Shares sum to 1 (0.333 each = on-ratio; the leading share is your over-provisioned leg). ratio_balance = weakest/strongest leg (1.0 = perfect). Legs use effective values: metal net of overflow, energy net of overflow + converter draw. 5s smoothed." },
  { title: "Map Metal Ownership", metricIds: ["extraction_t1", "extraction_t2"],
    note: "Metal extracted from map spots per player — one hue per player, darker shade = T2 mohos. The map-control war, in income terms." },
  { title: "Survival & Income", metricIds: ["units_alive", "m_income"],
    note: "units_alive doubles as the death detector — a series that flatlines to zero (or ends early) marks elimination; raw OBP counts dead frames as clean, so read OBP against this." },
  { title: "Sharing", metricIds: ["m_sent", "m_received", "e_sent"],
    note: "Cumulative resource transfers — the team-game 'feeder' economy (front players and leavers funnel metal to carries)." },
];
